# Connect to SQL Database

In [2]:
import pandas as pd 
from sqlalchemy import create_engine

In [12]:
# Load and read csv
csv_file = "./data/battles.csv"
got_battles = pd.read_csv(csv_file)

json_file = "./data/character-deaths.json"
character_deaths_uncleaned = pd.read_json(json_file)

csv_file3 = "./data/character-predictions.csv"
character_predictions = pd.read_csv(csv_file3)

csv_file4 = "./data/scripts.csv"
got_scripts = pd.read_csv(csv_file4)

csv_file5 = "./data/ratings.csv"
got_ratings = pd.read_csv(csv_file5)

ValueError: Unexpected character found when decoding 'null'

In [9]:
character_deaths

,Name,Allegiances,Death Year,Book of Death,Death Chapter,Book Intro Chapter,Gender,Nobility,GoT,CoK,SoS,FfC,DwD
0,Addam Marbrand,Lannister,NaN,NaN,NaN,56.0,1,1,1,1,1,1,0
1,Aegon Frey (Jinglebell),None,299.0,3.0,51.0,49.0,1,1,0,0,1,0,0
2,Aegon Targaryen,House Targaryen,NaN,NaN,NaN,5.0,1,1,0,0,0,0,1
3,Adrack Humble,House Greyjoy,300.0,5.0,20.0,20.0,1,1,0,0,0,0,1
4,Aemon Costayne,Lannister,NaN,NaN,NaN,NaN,1,1,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
912,Zollo,None,NaN,NaN,NaN,21.0,1,0,0,0,1,0,0
913,Yurkhaz zo Yunzak,None,300.0,5.0,59.0,47.0,1,0,0,0,0,0,1
914,Yezzan Zo Qaggaz,None,300.0,5.0,57.0,25.0,1,1,0,0,0,0,1
915,Torwynd the Tame,Wildling,300.0,5.0,73.0,73.0,1,0,0,0,1,0,0
916,Talbert Serry,Tyrell,300.0,4.0,29.0,29.0,1,1,0,0,0,1,0